// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    wordsFts,
    words,
    wordNotes,
    notesFtsAfterInsert,
    notesFtsAfterUpdate,
    notesFtsAfterDelete,
    idxNotesWord,
    idxWordsNormalized,
    idxWordsUpdated,
    ipaHighlights,
    wordLists,
    wordListItems,
    studyCards,
    practiceSessions,
    practiceAnswers,
    appMeta,
    settings,
    idxHighlightsWord,
    idxCardsDue,
    idxCardsBoxLapses,
  ];
  late final Shape0 wordsFts = Shape0(
    source: i0.VersionedVirtualTable(
      entityName: 'words_fts',
      moduleAndArgs: 'fts5(word_id UNINDEXED, headword, definition, example, notes, tokenize = \'unicode61 remove_diacritics 2\')',
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 words = Shape1(
    source: i0.VersionedTable(
      entityName: 'words',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 wordNotes = Shape2(
    source: i0.VersionedTable(
      entityName: 'word_notes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_20,
        _column_21,
        _column_17,
        _column_18,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger notesFtsAfterInsert = i1.Trigger(
    'CREATE TRIGGER notes_fts_after_insert AFTER INSERT ON word_notes BEGIN UPDATE words_fts SET notes = coalesce((SELECT group_concat(body, \' \') FROM word_notes WHERE word_id = new.word_id), \'\') WHERE word_id = new.word_id;END',
    'notes_fts_after_insert',
  );
  final i1.Trigger notesFtsAfterUpdate = i1.Trigger(
    'CREATE TRIGGER notes_fts_after_update AFTER UPDATE ON word_notes BEGIN UPDATE words_fts SET notes = coalesce((SELECT group_concat(body, \' \') FROM word_notes WHERE word_id = new.word_id), \'\') WHERE word_id = new.word_id;END',
    'notes_fts_after_update',
  );
  final i1.Trigger notesFtsAfterDelete = i1.Trigger(
    'CREATE TRIGGER notes_fts_after_delete AFTER DELETE ON word_notes BEGIN UPDATE words_fts SET notes = coalesce((SELECT group_concat(body, \' \') FROM word_notes WHERE word_id = old.word_id), \'\') WHERE word_id = old.word_id;END',
    'notes_fts_after_delete',
  );
  final i1.Index idxNotesWord = i1.Index(
    'idx_notes_word',
    'CREATE INDEX idx_notes_word ON word_notes (word_id)',
  );
  final i1.Index idxWordsNormalized = i1.Index(
    'idx_words_normalized',
    'CREATE INDEX idx_words_normalized ON words (headword_normalized)',
  );
  final i1.Index idxWordsUpdated = i1.Index(
    'idx_words_updated',
    'CREATE INDEX idx_words_updated ON words (updated_at DESC)',
  );
  late final Shape3 ipaHighlights = Shape3(
    source: i0.VersionedTable(
      entityName: 'ipa_highlights',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(end_grapheme > start_grapheme)',
        'CHECK(start_grapheme >= 0)',
      ],
      columns: [
        _column_5,
        _column_20,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 wordLists = Shape4(
    source: i0.VersionedTable(
      entityName: 'word_lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_28,
        _column_26,
        _column_29,
        _column_30,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 wordListItems = Shape5(
    source: i0.VersionedTable(
      entityName: 'word_list_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(list_id, word_id)'],
      columns: [_column_31, _column_20, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 studyCards = Shape6(
    source: i0.VersionedTable(
      entityName: 'study_cards',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(word_id)',
        'CHECK(box >= 0 AND box <= 6)',
      ],
      columns: [
        _column_20,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 practiceSessions = Shape7(
    source: i0.VersionedTable(
      entityName: 'practice_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 practiceAnswers = Shape8(
    source: i0.VersionedTable(
      entityName: 'practice_answers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_52,
        _column_20,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 appMeta = Shape9(
    source: i0.VersionedTable(
      entityName: 'app_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_57, _column_58],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 settings = Shape10(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxHighlightsWord = i1.Index(
    'idx_highlights_word',
    'CREATE INDEX idx_highlights_word ON ipa_highlights (word_id, target)',
  );
  final i1.Index idxCardsDue = i1.Index(
    'idx_cards_due',
    'CREATE INDEX idx_cards_due ON study_cards (due_at, suspended)',
  );
  final i1.Index idxCardsBoxLapses = i1.Index(
    'idx_cards_box_lapses',
    'CREATE INDEX idx_cards_box_lapses ON study_cards (box, lapses)',
  );
}

class Shape0 extends i0.VersionedVirtualTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get wordId =>
      columnsByName['word_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get headword =>
      columnsByName['headword']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get definition =>
      columnsByName['definition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get example =>
      columnsByName['example']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'word_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'headword',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'definition',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'example',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get headword =>
      columnsByName['headword']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get headwordNormalized =>
      columnsByName['headword_normalized']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partOfSpeech =>
      columnsByName['part_of_speech']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ipaUk =>
      columnsByName['ipa_uk']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ipaUs =>
      columnsByName['ipa_us']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get definition =>
      columnsByName['definition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get example =>
      columnsByName['example']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceAttribution =>
      columnsByName['source_attribution']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isFavourite =>
      columnsByName['is_favourite']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'headword',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'headword_normalized',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'part_of_speech',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ipa_uk',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ipa_us',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'definition',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'example',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'manual\'',
      defaultValue: const i1.CustomExpression('\'manual\''),
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_attribution',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_favourite',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_favourite IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wordId =>
      columnsByName['word_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pinned =>
      columnsByName['pinned']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'word_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES words(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pinned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (pinned IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wordId =>
      columnsByName['word_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get target =>
      columnsByName['target']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startGrapheme =>
      columnsByName['start_grapheme']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endGrapheme =>
      columnsByName['end_grapheme']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get colorToken =>
      columnsByName['color_token']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_grapheme',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_grapheme',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color_token',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get colorToken =>
      columnsByName['color_token']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iconKey =>
      columnsByName['icon_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get listId =>
      columnsByName['list_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wordId =>
      columnsByName['word_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'list_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES word_lists(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'added_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get wordId =>
      columnsByName['word_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get box =>
      columnsByName['box']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dueAt =>
      columnsByName['due_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get intervalDays =>
      columnsByName['interval_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get easeFactor =>
      columnsByName['ease_factor']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get repetitions =>
      columnsByName['repetitions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lapses =>
      columnsByName['lapses']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastReviewedAt =>
      columnsByName['last_reviewed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastResult =>
      columnsByName['last_result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get suspended =>
      columnsByName['suspended']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'box',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'due_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'interval_days',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<double> _column_36(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ease_factor',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 2.5',
      defaultValue: const i1.CustomExpression('2.5'),
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'repetitions',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'lapses',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_reviewed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_result',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'suspended',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (suspended IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gameId =>
      columnsByName['game_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceKind =>
      columnsByName['source_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get configJson =>
      columnsByName['config_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalRounds =>
      columnsByName['total_rounds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get correctRounds =>
      columnsByName['correct_rounds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get affectsScheduling =>
      columnsByName['affects_scheduling']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'game_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'config_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_rounds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'correct_rounds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'affects_scheduling',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (affects_scheduling IN (0, 1))',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wordId =>
      columnsByName['word_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get roundIndex =>
      columnsByName['round_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get result =>
      columnsByName['result']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get responseMs =>
      columnsByName['response_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get answeredAt =>
      columnsByName['answered_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES practice_sessions(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'round_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'result',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'response_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'answered_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ttsLocale =>
      columnsByName['tts_locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get ttsRate =>
      columnsByName['tts_rate']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ttsPitch =>
      columnsByName['tts_pitch']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get autoplayOnOpen =>
      columnsByName['autoplay_on_open']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyGoal =>
      columnsByName['daily_goal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderEnabled =>
      columnsByName['reminder_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderTimeMinutes =>
      columnsByName['reminder_time_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get promptSide =>
      columnsByName['prompt_side']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lookupEnabled =>
      columnsByName['lookup_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reviewSchedule =>
      columnsByName['review_schedule']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get againRepeats =>
      columnsByName['again_repeats']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'system\'',
      defaultValue: const i1.CustomExpression('\'system\''),
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tts_locale',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'en-GB\'',
      defaultValue: const i1.CustomExpression('\'en-GB\''),
    );
i1.GeneratedColumn<double> _column_62(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tts_rate',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 0.5',
      defaultValue: const i1.CustomExpression('0.5'),
    );
i1.GeneratedColumn<double> _column_63(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tts_pitch',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 1.0',
      defaultValue: const i1.CustomExpression('1.0'),
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'autoplay_on_open',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (autoplay_on_open IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'daily_goal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 20',
      defaultValue: const i1.CustomExpression('20'),
    );
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (reminder_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_time_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'prompt_side',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'word_first\'',
      defaultValue: const i1.CustomExpression('\'word_first\''),
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'lookup_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (lookup_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'review_schedule',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[0,1,2,4,7,15,30]\'',
      defaultValue: const i1.CustomExpression('\'[0,1,2,4,7,15,30]\''),
    );
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'again_repeats',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
